CC=gcc
CXX=g++
CXXFLAGS=-std=c++11 -Wall -pedantic

word_puzzle_list.x: word_puzzle_list.h word_puzzle_list.cpp rotation.cpp
	$(CXX) $(CXXFLAGS) -I. -o $@ word_puzzle_list.cpp rotation.cpp

.SUFFIXES: .x

.PHONY : clean

clean:
	rm -f *.o *.x core.*

%.x : %.c
	$(CC) -o $@ $<
%.x : %.cpp
	$(CXX) $(CXXFLAGS) -o $@ $<
